### ISSUE TITLE
Default config in ah-sequelize-plugin leaks to production

### ISSUE THREAD

**Issue by submitteddenied** [evantahler/ah-sequelize-plugin#10]
Just now, when deploying to production, we saw that the default value for `replication` was being used (and the mysql connection could not be established!).

Our config looked like this:
```
exports.production = {
  sequelize: function(api){
    return {
      "logging"     : false,
      "database"    : "<database>",
      "dialect"     : "mysql",
      "port"        : 3306,
      "host"        : "<hostname>",
      "username"    : "<user>",
      "password"    : "<pass>",
      "pool": { maxConnections: 200, maxIdleTime: 30000}
    }
  }
}
```

Since, the `replication` key did not exist, the actionhero config system merged our production config with the defaults in `config/sequelize.js` (from this project), which obviously don't work.

```
    ...
      "replication" : {
        "write": {
          "host"     : "127.0.0.1", 
          "username" : "root", 
          "password" : "",
          "pool"     : {}
        },
        "read": [
          {
            "host"     : "127.0.0.1", 
            "username" : "root", 
            "password" : "",
            "pool"     : {}
          }
        ]
      }
   ...
```

Is there a better way to show what configuration is available without potentially leaking config through to production? Maybe a block comment in config.js or just more detail in the README? We could also just direct people to the sequelize docs, since those will be most up to date.

**Comment by evantahler** [comment]
I think the correct thing to do ([which I have just done](https://github.com/evantahler/ah-sequelize-plugin/commit/bdf57103bbf992cfbc6d731879f1bd6197e09bd9)) is remove any environment-specific configs from the package's config file.  This way there's no danger of extra keys being added.  I will link to the docs.

V0.4.1 up on NPM

Thanks for catching this!
