### ISSUE TITLE
New Maintainers!

### ISSUE THREAD

**Issue by evantahler** [evantahler/ah-sequelize-plugin#20]
Hey Folks- 

I don't use sequelize that much these days, and I'm a bit out of the loop on best-practices.  To that end, I'd like to make both @bakavic and @submitteddenied maintainers of this project!   This includes admin powers on this repo, and the NPM package.

What are your thoughts?

**Comment by submitteddenied** [comment]
Thanks! I'd be happy to do it :)

**Comment by evantahler** [comment]
@submitteddenied added here! What's your NPM name?

**Comment by submitteddenied** [comment]
It's also submitteddenied

**Comment by evantahler** [comment]
```
[23:22:14] evantahler@Opsimus-2 [~/PROJECTS/ah-plugins/ah-sequelize-plugin] (master)
> npm owner add submitteddenied
+ submitteddenied (ah-sequelize-plugin)
```

Enjoy! Don't break it!

**Comment by kytwb** [comment]
Looking forward for updates :+1: Good luck to the new maintainers!

**Comment by evantahler** [comment]
@bakavic never commented, so just @submitteddenied is in charge :D

**Comment by kytwb** [comment]
@evantahler looks like we'll have to wait fot @submitteddenied to come back from holiday to merge #19

**Comment by bakavic** [comment]
@evantahler ah, somehow I missed this issue - yup, I wouldn't mind helping out!

**Comment by evantahler** [comment]
@bakavic yay! What's your NPM name?

**Comment by bakavic** [comment]
@evantahler it's `bakavic` as well :)

**Comment by evantahler** [comment]
```
> npm owner add bakavic
+ bakavic (ah-sequelize-plugin)
```

**Comment by evantahler** [comment]
![screen shot 2015-06-02 at 11 35 01 am](https://cloud.githubusercontent.com/assets/303226/7933987/6acc0eaa-091b-11e5-8142-424d7c0ecd40.png)

**Comment by evantahler** [comment]
Have fun!

**Comment by kytwb** [comment]
Congrats @bakavic @submitteddenied :+1:
