### ISSUE TITLE
Encourage usage of seeders instead of sequelize-fixtures

### ISSUE THREAD

**Issue by kytwb** [evantahler/ah-sequelize-plugin#39]
I was just wondering if it still makes sense to encourage using sequelize-fixtures instead of using sequelize native seeders support? Would love your input @evantahler.

**Comment by evantahler** [comment]
I have no opinions on this.. I don't use this package any more.

**Comment by kytwb** [comment]
Ok so after looking at it a bit more, I think it still makes sense to have fixtures and seeders, different use cases.
