### ISSUE TITLE
Running `undoMigration` actually reverses ALL migrations

### ISSUE THREAD

**Issue by submitteddenied** [evantahler/ah-sequelize-plugin#9]
This is (in my opinion) a bug in Sequelize, where the default behaviour when `{method: "down"}` is to execute the `down()` for _all_ migrations.

Not sure how you want to proceed here, but we could:
  * Submit a PR to Sequelize to add a `limit` option to migrations, and then we pass `{limit: 1}` or similar
    * I intend to do this, but we will be held to Sequelize's update schedule
  * Change docs to mention that `undoMigration` undoes everything
  * Remove the `undoMigration` method, as it's probably not what most people want
  * Something else? Reimplement how the Sequelize migrator executes `down` migrations? Drop the DB and rerun all but one `up` migration?

**Comment by evantahler** [comment]
Haha, you probably never want to drop anything... especially as you might be migrating production! 

I would suggest:
1) change the docs ASAP
2) reach out to the sequelize team about this.  reading [this](https://sequelize.readthedocs.org/en/latest/docs/migrations/) it seems that they intended (and have tested) that migrate(down) should only do one migration.  I'll bet it is implemented incorrectly here.

**Comment by submitteddenied** [comment]
So according to [the Sequelize team](The Sequelize core migrator is severely broken and has been rewritten in https://github.com/sequelize/umzug)

> The Sequelize core migrator is severely broken and has been rewritten in https://github.com/sequelize/umzug

They have replaced the migration functionality in `sequelize-cli` with Umzug and will apparently be removing the migrator from Sequelize itself "in a version or two".

I'll PR changing the docs in ah-sequelize-plugin shortly, and endorse the use of `sequelize-cli`.

**Comment by evantahler** [comment]
Good research! 
And scary.

I look forward to the update!

**Comment by bakavic** [comment]
I think this issue has already been solved by the move to umzug. Closing.
